
language: smalltalk
sudo: false

os:
  - linux
#  - osx

smalltalk:
  - Pharo64-8.0
  - Pharo64-9.0
  
matrix:
  fast_finish: true
  
services:
  - docker

before_install:
  - docker run -p 127.0.0.1:6379:6379 -v redis.conf:/etc/redis/redis.conf redislabs/rejson /etc/redis/redis.conf
