
language: smalltalk
sudo: true

os:
  - linux
#  - osx

smalltalk:
  - Pharo64-8.0
  - Pharo64-9.0
  
services:
  - docker

before_install:
  - docker pull redislabs/rejson
  - docker run -p 6379:6379   redislabs/rejson --requirepass goodPassword & 
  - docker ps -a
  - sleep 10
