SystemOrganization addCategory: #'Voyage-Redis-Core'!
SystemOrganization addCategory: #'Voyage-Redis-Core-base'!
SystemOrganization addCategory: #'Voyage-Redis-Core-exception'!
SystemOrganization addCategory: #'Voyage-Redis-Core-magritte'!
SystemOrganization addCategory: #'Voyage-Redis-Core-operation'!
SystemOrganization addCategory: #'Voyage-Redis-Core-pooling'!
SystemOrganization addCategory: #'Voyage-Redis-Core-utilities'!
